name: pipline
Agent: Large
Jabber: cje2
Application_Name:
Artifact_Location:
Artifact_Name:
Artifact_Version: 
tools:
  Java: 
  Ant: 
Build:
   options: 
   command: 
   file_name: 
   Notify_When:
        Failure: True
        Pass: True
        Unstable: False
    Notify_How:
        Failure: True
        Pass: True
        Unstable: False
   Notify_Who:
        Failure: True
        Pass: True
        Unstable: False
Dev_Env: 
  command: sh bla bla bla bl
   Notify_When:
        Failure: True
        Pass: True
        Unstable: False
    Notify_How:
        Failure: True
        Pass: True
        Unstable: False
   Notify_Who:
        Failure: True
        Pass: True
        Unstable: False
  
  
